import React from 'react';
import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/styles/theme-provider';
import Header from '@/components/header';
import { GlobalStoreProvider } from '@/store/global.store';
import LocaleProvider from '@/localization/locale-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Next App with Tailwind and shadcn/ui',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={inter.className}>
                <GlobalStoreProvider>
                    <LocaleProvider>
                        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                            <Header />
                            {children}
                        </ThemeProvider>
                    </LocaleProvider>
                </GlobalStoreProvider>
            </body>
        </html>
    );
}
